---
name: Test-Block
version: 0.09
author:
  - Adrian Howard <adrianh@quietstars.com>
abstract: Specify fine granularity test plans
license: perl
requires:
  Test::Builder: 0.17
  Test::Builder::Tester: 1.01
  Test::Exception: 0.15
  Test::More: 0.47
  perl: 5.6.1
provides:
  Test::Block:
    file: lib/Test/Block.pm
    version: 0.09
  Test::Block::Plan:
    file: lib/Test/Block.pm
    version: 0.09
generated_by: Module::Build version 0.2611
