# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Block
version:      0.05
version_from: lib/Test/Block.pm
installdirs:  site
requires:
    Test::Builder:                 0.17
    Test::Builder::Tester:         0.09
    Test::Exception:               0.15
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
