---
abstract: 'DEPRECIATED: Specify fine granularity test plans'
author:
  - 'Adrian Howard <adrianh@quietstars.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Block
provides:
  Test::Block:
    file: lib/Test/Block.pm
    version: 0.13
  Test::Block::Plan:
    file: lib/Test/Block.pm
    version: 0
requires:
  Test::Builder: 0.17
  Test::Builder::Tester: 1.01
  Test::Exception: 0.15
  Test::More: 0.47
  perl: v5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.13
